In [89]:
# #Q1
# How many unknown ("?) values are present in the dataset? Remove/Delete unknown ("?) values present in the dataset to make it null value.
# Remove/Delete - means it will show NAN in place of "?"
# Note: If there is no value present in the dataset it is represented as NAN(read pandas documentation for all the other ways to represent null values) in data

In [90]:
import pandas as pd
df=pd.read_csv(r"C:\Users\indee\Desktop\Machine Learning Practice\Machine_Learning_Practice\Pandas\w1-ga1\Week1_GA_dataset.csv")
df

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2022-09-30,2022,Bridgeport,153660.0,322000.0,?,Detached House,3,3,917.0,1.003979,North
9996,2022-09-30,2022,Bridgeport,109820.0,340000.0,?,Duplex,4,4,1416.0,1.003979,North
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South
9998,2022-09-30,2022,NaN,216420.0,415000.0,Single Family,Detached House,3,3,1014.0,1.003979,North
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East

In [91]:
df.columns

Index(['Date', 'Year', 'Locality', 'Estimated Value', 'Sale Price', 'Property',
       'Residential', 'num_rooms', 'num_bathrooms', 'carpet_area',
       'property_tax_rate', 'Face'],
      dtype='str')

In [92]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               10000 non-null  str
 1   Year               10000 non-null  int64
 2   Locality           8747 non-null   str
 3   Estimated Value    8757 non-null   float64
 4   Sale Price         10000 non-null  float64
 5   Property           10000 non-null  str
 6   Residential        10000 non-null  str
 7   num_rooms          10000 non-null  int64
 8   num_bathrooms      10000 non-null  int64
 9   carpet_area        8771 non-null   float64
 10  property_tax_rate  10000 non-null  float64
 11  Face               10000 non-null  str
dtypes: float64(4), int64(3), str(5)
memory usage: 937.6 KB

In [93]:
(df == "?").sum()

Date                    0
Year                    0
Locality                0
Estimated Value         0
Sale Price              0
Property             1823
Residential             0
num_rooms               0
num_bathrooms           0
carpet_area             0
property_tax_rate       0
Face                    0
dtype: int64

In [94]:
import numpy as np
df_copy=df.copy()
df_copy['Property'] = df_copy['Property'].replace("?", np.nan)

In [95]:
df_copy['Property']

0       Single Family
1          Two Family
2       Single Family
3       Single Family
4                 NaN
            ...
9995              NaN
9996              NaN
9997    Single Family
9998    Single Family
9999    Single Family
Name: Property, Length: 10000, dtype: str

In [96]:
#Q2 
#Shape of the dataset
df_copy.shape

(10000, 12)

In [97]:
#Q3
# What is the value present at the 692th indexed row and 0th indexed column in the data ?

# dataframe[692,0] (simpy saying this in a matrix)
# rows/ columns starts indexing from zero(0) in python

#using loc and iloc
#loc
df_copy.loc[692,['Date']]

Date    2009-11-16
Name: 692, dtype: str

In [98]:
#iloc
df_copy.iloc[692,0]

'2009-11-16'

In [99]:
#Q4
# What is the value present at the 546th indexed row and 7th indexed column in the data ?
#  dataframe[546,7] (simpy saying this in a matrix)
#  rows/ columns starts indexing from zero(0) in python

df_copy.iloc[546,7]

np.int64(3)

In [ ]:
#Q6
# What are the unique values present in the Locality feature of the dataset?
df['Locality'].unique()

<StringArray>
[    'Waterbury',    'Bridgeport',     'Greenwich',       'Norwalk',
             nan,     'Fairfield', 'West Hartford',      'Stamford']
Length: 8, dtype: str

In [101]:
#Q5
#Which of the following features have missing(NaN) values present in the dataset?
#(Note: compute after removing "?")
for i in df_copy.columns:
    if df_copy[i].isnull().any():
        print(i)

Locality
Estimated Value
Property
carpet_area

In [102]:
#Q7
# Which of the following feature has most missing(NaN) values present in the dataset?
#  (Note: compute after removing "?") 

df_copy.isna().sum()

Date                    0
Year                    0
Locality             1253
Estimated Value      1243
Sale Price              0
Property             1823
Residential             0
num_rooms               0
num_bathrooms           0
carpet_area          1229
property_tax_rate       0
Face                    0
dtype: int64

In [103]:
#Q8
# Drop all the samples(rows) with missing values strictly greater than 2. How many samples remains after that ?
#  (Note: compute after removing "?")

In [104]:
# val=df_copy.shape[0]
# val


# for i in range(0,val):
#     if df_copy.iloc[i,:].isna().sum()>2:
#         df_copy.drop(i,inplace=True)
df_copy

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,NaN,Detached House,3,2,1092.0,1.025953,East
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2022-09-30,2022,Bridgeport,153660.0,322000.0,NaN,Detached House,3,3,917.0,1.003979,North
9996,2022-09-30,2022,Bridgeport,109820.0,340000.0,NaN,Duplex,4,4,1416.0,1.003979,North
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South
9998,2022-09-30,2022,NaN,216420.0,415000.0,Single Family,Detached House,3,3,1014.0,1.003979,North
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East

In [105]:
selector=(df_copy.isna().sum(axis=1)>2)
counts=selector.value_counts()
counts

False    9917
True       83
Name: count, dtype: int64

In [106]:
df_copy[~selector]
#df_copy

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,NaN,Detached House,3,2,1092.0,1.025953,East
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2022-09-30,2022,Bridgeport,153660.0,322000.0,NaN,Detached House,3,3,917.0,1.003979,North
9996,2022-09-30,2022,Bridgeport,109820.0,340000.0,NaN,Duplex,4,4,1416.0,1.003979,North
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South
9998,2022-09-30,2022,NaN,216420.0,415000.0,Single Family,Detached House,3,3,1014.0,1.003979,North
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East

In [ ]:
#Q9
# # Drop all the samples(rows) with missing values in the original dataframe. How many samples remains after that ?
#  (Note: compute after removing "?") 
df_new = df_copy.dropna(axis=0) #axis=0 by default
df_new

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
5,2009-01-02,2009,Greenwich,2868880.0,3300000.0,Single Family,Detached House,3,1,1039.0,1.025953,North
...,...,...,...,...,...,...,...,...,...,...,...,...
9986,2022-09-28,2022,Norwalk,305820.0,535000.0,Single Family,Detached House,3,2,1080.0,1.003979,West
9987,2022-09-28,2022,Norwalk,450510.0,677000.0,Single Family,Detached House,3,1,1000.0,1.003979,North
9993,2022-09-30,2022,West Hartford,121870.0,235000.0,Single Family,Detached House,3,2,1087.0,1.003979,South
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East