In [1]:
import pandas as pd

In [3]:
df=pd.read_csv(r"C:\Users\indee\Desktop\Machine Learning Practice\Machine_Learning_Practice\Pandas\pa1\Preprocessing1.csv")

In [4]:
df

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Month,WeekDay,Day
0,Jet Airways,Delhi,Banglore,DEL → BOM → COK,20:00,04:25 10 Jun,26h 35m,1 stop,In-flight meal not included,14924,6,Thursday,6.0
1,Jet Airways,Delhi,Cochin,DEL → BOM → COK,16:00,19:00 10 Jun,27h,1 stop,In-flight meal not included,10577,6,Sunday,9.0
2,Jet Airways,Mumbai,Hyderabad,BOM → HYD,19:35,21:05,1h 30m,non-stop,No info,5678,3,Friday,15.0
3,Multiple carriers,Delhi,Banglore,DEL → BOM → COK,18:55,01:30 16 Jun,15h 10m,1 stop,In-flight meal not included,7408,5,Monday,6.0
4,Air India,Delhi,Cochin,DEL → COK,17:10,17:55,8h 20m,non-stop,No info,6724,6,Monday,24.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9445,Air India,Banglore,Cochin,BLR → MAA → DEL,19:30,19:50,8h 55m,1 stop,In-flight meal not included,5932,6,Wednesday,12.0
9446,IndiGo,Delhi,Cochin,DEL → BOM → COK,17:00,21:00,8h 35m,1 stop,No info,6838,3,Sunday,3.0
9447,Multiple carriers,Delhi,Cochin,DEL → BOM → COK,07:05,19:45,15h 15m,1 stop,No info,12615,3,Saturday,9.0
9448,Jet Airways,Kolkata,Banglore,CCU → BOM → BLR,08:20,19:50,12h 5m,1 stop,No info,10844,5,Saturday,18.0
9449,Air India,Kolkata,Banglore,CCU → GAU → IMF → DEL → BLR,14:30,23:15,8h 45m,3 stops,No info,15145,5,Thursday,9.0

In [14]:
df['Price'].isnull().any()

np.False_

In [16]:
df['Price'].mean()

np.float64(9027.895555555555)

In [ ]:
#Q1
#What is the average of the flight ticket price? Write your answer correct to two decimal places.
round(df['Price'].mean(), 3)

np.float64(9027.896)

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9450 entries, 0 to 9449
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          9450 non-null   str
 1   Source           9450 non-null   str
 2   Destination      9450 non-null   str
 3   Route            9449 non-null   str
 4   Dep_Time         9450 non-null   str
 5   Arrival_Time     9450 non-null   str
 6   Duration         9450 non-null   str
 7   Total_Stops      9250 non-null   str
 8   Additional_Info  9450 non-null   str
 9   Price            9450 non-null   int64
 10  Month            9450 non-null   int64
 11  WeekDay          9450 non-null   str
 12  Day              9214 non-null   float64
dtypes: float64(1), int64(2), str(10)
memory usage: 959.9 KB

In [ ]:
#Q2
#During which month did the highest number of flights occur? Months are represented by numerical codes, with January corresponding to 1, February to 2, and so forth.
df['Month'].value_counts()

Month
5    3092
6    3044
3    2388
4     926
Name: count, dtype: int64

In [23]:
#Q3
#Is the average price of flight tickets higher on weekends (Saturday and Sunday) or on weekdays (Remaining 5 days)?

#Split the data into two groups: weekend and weekday
df['WeekDay']

0        Thursday
1          Sunday
2          Friday
3          Monday
4          Monday
          ...
9445    Wednesday
9446       Sunday
9447     Saturday
9448     Saturday
9449     Thursday
Name: WeekDay, Length: 9450, dtype: str

In [28]:
#
selector = df['WeekDay'].isin(['Saturday', 'Sunday'])
weekends=df[selector]
weekends
# weekdays=df[df['WeekDay']]
#weekdays

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Month,WeekDay,Day
1,Jet Airways,Delhi,Cochin,DEL → BOM → COK,16:00,19:00 10 Jun,27h,1 stop,In-flight meal not included,10577,6,Sunday,9.0
5,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,08:55,21:20,12h 25m,1 stop,In-flight meal not included,11087,3,Saturday,9.0
7,SpiceJet,Delhi,Banglore,DEL → MAA → COK,16:30,11:20,12h 10m,1 stop,No info,6297,5,Sunday,12.0
16,Air India,Banglore,Delhi,BLR → DEL,17:00,19:45,2h 45m,non-stop,No info,5438,5,Sunday,12.0
19,Jet Airways,Delhi,Cochin,DEL → BOM → COK,07:10,12:35 16 Jun,9h,1 stop,In-flight meal not included,10262,3,Sunday,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9436,IndiGo,Banglore,Delhi,BLR → DEL,11:10,15:50,2h 55m,non-stop,In-flight meal not included,4423,6,Saturday,15.0
9441,Jet Airways,Delhi,Cochin,DEL → BOM → COK,07:05,04:25 16 Jun,12h 10m,1 stop,No info,10262,6,Saturday,15.0
9446,IndiGo,Delhi,Cochin,DEL → BOM → COK,17:00,21:00,8h 35m,1 stop,No info,6838,3,Sunday,3.0
9447,Multiple carriers,Delhi,Cochin,DEL → BOM → COK,07:05,19:45,15h 15m,1 stop,No info,12615,3,Saturday,9.0
9448,Jet Airways,Kolkata,Banglore,CCU → BOM → BLR,08:20,19:50,12h 5m,1 stop,No info,10844,5,Saturday,18.0

In [32]:
#Type 2
weekdays=df[ (df['WeekDay']=='Monday') | (df['WeekDay']=='Tuesday') | (df['WeekDay']=='Wednesday') | (df['WeekDay']=='Thursday') | (df['WeekDay']=='Friday') ]
weekdays

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Month,WeekDay,Day
0,Jet Airways,Delhi,Banglore,DEL → BOM → COK,20:00,04:25 10 Jun,26h 35m,1 stop,In-flight meal not included,14924,6,Thursday,6.0
2,Jet Airways,Mumbai,Hyderabad,BOM → HYD,19:35,21:05,1h 30m,non-stop,No info,5678,3,Friday,15.0
3,Multiple carriers,Delhi,Banglore,DEL → BOM → COK,18:55,01:30 16 Jun,15h 10m,1 stop,In-flight meal not included,7408,5,Monday,6.0
4,Air India,Delhi,Cochin,DEL → COK,17:10,17:55,8h 20m,non-stop,No info,6724,6,Monday,24.0
6,Jet Airways,Kolkata,Banglore,CCU → BOM → BLR,21:10,04:40 02 Apr,7h 30m,1 stop,No info,13364,4,Monday,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9442,Multiple carriers,Delhi,Cochin,DEL → BOM → COK,07:05,15:30,8h 25m,1 stop,No info,12537,3,Wednesday,27.0
9443,Jet Airways,Mumbai,Hyderabad,BOM → HYD,19:35,21:05,1h 30m,non-stop,In-flight meal not included,2071,4,Wednesday,3.0
9444,Jet Airways,Banglore,Cochin,BLR → DEL,21:50,22:50,5h 45m,non-stop,No info,7229,6,Monday,3.0
9445,Air India,Banglore,Cochin,BLR → MAA → DEL,19:30,19:50,8h 55m,1 stop,In-flight meal not included,5932,6,Wednesday,12.0
9449,Air India,Kolkata,Banglore,CCU → GAU → IMF → DEL → BLR,14:30,23:15,8h 45m,3 stops,No info,15145,5,Thursday,9.0

In [34]:
df.loc[df['Month']]

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Month,WeekDay,Day
6,Jet Airways,Kolkata,Banglore,CCU → BOM → BLR,21:10,04:40 02 Apr,7h 30m,1 stop,No info,13364,4,Monday,1.0
6,Jet Airways,Kolkata,Banglore,CCU → BOM → BLR,21:10,04:40 02 Apr,7h 30m,1 stop,No info,13364,4,Monday,1.0
3,Multiple carriers,Delhi,Banglore,DEL → BOM → COK,18:55,01:30 16 Jun,15h 10m,1 stop,In-flight meal not included,7408,5,Monday,6.0
5,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,08:55,21:20,12h 25m,1 stop,In-flight meal not included,11087,3,Saturday,9.0
6,Jet Airways,Kolkata,Banglore,CCU → BOM → BLR,21:10,04:40 02 Apr,7h 30m,1 stop,No info,13364,4,Monday,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6,Jet Airways,Kolkata,Banglore,CCU → BOM → BLR,21:10,04:40 02 Apr,7h 30m,1 stop,No info,13364,4,Monday,1.0
3,Multiple carriers,Delhi,Banglore,DEL → BOM → COK,18:55,01:30 16 Jun,15h 10m,1 stop,In-flight meal not included,7408,5,Monday,6.0
3,Multiple carriers,Delhi,Banglore,DEL → BOM → COK,18:55,01:30 16 Jun,15h 10m,1 stop,In-flight meal not included,7408,5,Monday,6.0
5,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,08:55,21:20,12h 25m,1 stop,In-flight meal not included,11087,3,Saturday,9.0
5,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,08:55,21:20,12h 25m,1 stop,In-flight meal not included,11087,3,Saturday,9.0

In [37]:
val=weekends['Price'].mean()
val1=weekdays['Price'].mean()
print(val,val1)

9058.016077170418 9015.219666215608

In [36]:
weekdays

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Month,WeekDay,Day
0,Jet Airways,Delhi,Banglore,DEL → BOM → COK,20:00,04:25 10 Jun,26h 35m,1 stop,In-flight meal not included,14924,6,Thursday,6.0
2,Jet Airways,Mumbai,Hyderabad,BOM → HYD,19:35,21:05,1h 30m,non-stop,No info,5678,3,Friday,15.0
3,Multiple carriers,Delhi,Banglore,DEL → BOM → COK,18:55,01:30 16 Jun,15h 10m,1 stop,In-flight meal not included,7408,5,Monday,6.0
4,Air India,Delhi,Cochin,DEL → COK,17:10,17:55,8h 20m,non-stop,No info,6724,6,Monday,24.0
6,Jet Airways,Kolkata,Banglore,CCU → BOM → BLR,21:10,04:40 02 Apr,7h 30m,1 stop,No info,13364,4,Monday,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9442,Multiple carriers,Delhi,Cochin,DEL → BOM → COK,07:05,15:30,8h 25m,1 stop,No info,12537,3,Wednesday,27.0
9443,Jet Airways,Mumbai,Hyderabad,BOM → HYD,19:35,21:05,1h 30m,non-stop,In-flight meal not included,2071,4,Wednesday,3.0
9444,Jet Airways,Banglore,Cochin,BLR → DEL,21:50,22:50,5h 45m,non-stop,No info,7229,6,Monday,3.0
9445,Air India,Banglore,Cochin,BLR → MAA → DEL,19:30,19:50,8h 55m,1 stop,In-flight meal not included,5932,6,Wednesday,12.0
9449,Air India,Kolkata,Banglore,CCU → GAU → IMF → DEL → BLR,14:30,23:15,8h 45m,3 stops,No info,15145,5,Thursday,9.0

In [ ]:
#Q4
#Two of the entries in the 'Additional_Info' column are 'No info' and 'No Info'. Replace all occurrences of 'No Info' with 'No info'. How many flights fall under airline 'IndiGo' and have 'No info' as additional information?

In [43]:
#selector= (df['Additional_Info'] == 'No Info')
df['Additional_Info'] = df['Additional_Info'].replace('No Info', 'No info',inplace=True)
df

C:\Users\indee\AppData\Local\Temp\ipykernel_31028\3244178958.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Additional_Info'] = df['Additional_Info'].replace('No Info', 'No info',inplace=True)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Month,WeekDay,Day
0,Jet Airways,Delhi,Banglore,DEL → BOM → COK,20:00,04:25 10 Jun,26h 35m,1 stop,In-flight meal not included,14924,6,Thursday,6.0
1,Jet Airways,Delhi,Cochin,DEL → BOM → COK,16:00,19:00 10 Jun,27h,1 stop,In-flight meal not included,10577,6,Sunday,9.0
2,Jet Airways,Mumbai,Hyderabad,BOM → HYD,19:35,21:05,1h 30m,non-stop,No info,5678,3,Friday,15.0
3,Multiple carriers,Delhi,Banglore,DEL → BOM → COK,18:55,01:30 16 Jun,15h 10m,1 stop,In-flight meal not included,7408,5,Monday,6.0
4,Air India,Delhi,Cochin,DEL → COK,17:10,17:55,8h 20m,non-stop,No info,6724,6,Monday,24.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9445,Air India,Banglore,Cochin,BLR → MAA → DEL,19:30,19:50,8h 55m,1 stop,In-flight meal not included,5932,6,Wednesday,12.0
9446,IndiGo,Delhi,Cochin,DEL → BOM → COK,17:00,21:00,8h 35m,1 stop,No info,6838,3,Sunday,3.0
9447,Multiple carriers,Delhi,Cochin,DEL → BOM → COK,07:05,19:45,15h 15m,1 stop,No info,12615,3,Saturday,9.0
9448,Jet Airways,Kolkata,Banglore,CCU → BOM → BLR,08:20,19:50,12h 5m,1 stop,No info,10844,5,Saturday,18.0
9449,Air India,Kolkata,Banglore,CCU → GAU → IMF → DEL → BLR,14:30,23:15,8h 45m,3 stops,No info,15145,5,Thursday,9.0

In [44]:
df['Additional_Info'].value_counts()

Additional_Info
No info                         7378
In-flight meal not included     1750
No check-in baggage included     298
1 Long layover                    13
Change airports                    5
2 Long layover                     3
1 Short layover                    2
Business class                     1
Name: count, dtype: int64

In [51]:
selector= (df['Additional_Info'].isin(['No info']) & (df['Airline']=='IndiGo'))
val=df[selector]

In [52]:
val.shape

(1650, 13)

In [53]:
#Q5
#Convert the values of 'Duration' into seconds. Enter the average duration (in seconds) of a flight. Enter your answer correct to two decimal places.

df['Duration']

0       26h 35m
1           27h
2        1h 30m
3       15h 10m
4        8h 20m
         ...
9445     8h 55m
9446     8h 35m
9447    15h 15m
9448     12h 5m
9449     8h 45m
Name: Duration, Length: 9450, dtype: str

In [54]:
#Time Delta

df['Duration_td'] = pd.to_timedelta(df['Duration'].str.replace('h', ' hours ').str.replace('m', ' minutes'))

In [55]:
df['Duration_td']

0      1 days 02:35:00
1      1 days 03:00:00
2      0 days 01:30:00
3      0 days 15:10:00
4      0 days 08:20:00
             ...
9445   0 days 08:55:00
9446   0 days 08:35:00
9447   0 days 15:15:00
9448   0 days 12:05:00
9449   0 days 08:45:00
Name: Duration_td, Length: 9450, dtype: timedelta64[us]

In [57]:
df['Duration_td'].dt.total_seconds().mean()

np.float64(38957.93650793651)

In [ ]:
#Q6

df['Dep_Time']

0       20:00
1       16:00
2       19:35
3       18:55
4       17:10
        ...
9445    19:30
9446    17:00
9447    07:05
9448    08:20
9449    14:30
Name: Dep_Time, Length: 9450, dtype: str

In [63]:
vals=df['Arrival_Time'].str.split(':')
df_copy=df.copy()

In [75]:
df_copy['Arrival_time_hr']=vals.str[0].astype(int)
df_copy

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Month,WeekDay,Day,Duration_td,Arrival_time_hr,Dep_Time_hr
0,Jet Airways,Delhi,Banglore,DEL → BOM → COK,20:00,04:25 10 Jun,26h 35m,1 stop,In-flight meal not included,14924,6,Thursday,6.0,1 days 02:35:00,4,20
1,Jet Airways,Delhi,Cochin,DEL → BOM → COK,16:00,19:00 10 Jun,27h,1 stop,In-flight meal not included,10577,6,Sunday,9.0,1 days 03:00:00,19,16
2,Jet Airways,Mumbai,Hyderabad,BOM → HYD,19:35,21:05,1h 30m,non-stop,No info,5678,3,Friday,15.0,0 days 01:30:00,21,19
3,Multiple carriers,Delhi,Banglore,DEL → BOM → COK,18:55,01:30 16 Jun,15h 10m,1 stop,In-flight meal not included,7408,5,Monday,6.0,0 days 15:10:00,1,18
4,Air India,Delhi,Cochin,DEL → COK,17:10,17:55,8h 20m,non-stop,No info,6724,6,Monday,24.0,0 days 08:20:00,17,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9445,Air India,Banglore,Cochin,BLR → MAA → DEL,19:30,19:50,8h 55m,1 stop,In-flight meal not included,5932,6,Wednesday,12.0,0 days 08:55:00,19,19
9446,IndiGo,Delhi,Cochin,DEL → BOM → COK,17:00,21:00,8h 35m,1 stop,No info,6838,3,Sunday,3.0,0 days 08:35:00,21,17
9447,Multiple carriers,Delhi,Cochin,DEL → BOM → COK,07:05,19:45,15h 15m,1 stop,No info,12615,3,Saturday,9.0,0 days 15:15:00,19,7
9448,Jet Airways,Kolkata,Banglore,CCU → BOM → BLR,08:20,19:50,12h 5m,1 stop,No info,10844,5,Saturday,18.0,0 days 12:05:00,19,8
9449,Air India,Kolkata,Banglore,CCU → GAU → IMF → DEL → BLR,14:30,23:15,8h 45m,3 stops,No info,15145,5,Thursday,9.0,0 days 08:45:00,23,14

In [76]:
vals1=df['Dep_Time'].str.split(':')
vals1

0       [20, 00]
1       [16, 00]
2       [19, 35]
3       [18, 55]
4       [17, 10]
          ...
9445    [19, 30]
9446    [17, 00]
9447    [07, 05]
9448    [08, 20]
9449    [14, 30]
Name: Dep_Time, Length: 9450, dtype: object

In [77]:
df_copy['Dep_Time_hr']=vals1.str[0].astype(int)
df_copy

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Month,WeekDay,Day,Duration_td,Arrival_time_hr,Dep_Time_hr
0,Jet Airways,Delhi,Banglore,DEL → BOM → COK,20:00,04:25 10 Jun,26h 35m,1 stop,In-flight meal not included,14924,6,Thursday,6.0,1 days 02:35:00,4,20
1,Jet Airways,Delhi,Cochin,DEL → BOM → COK,16:00,19:00 10 Jun,27h,1 stop,In-flight meal not included,10577,6,Sunday,9.0,1 days 03:00:00,19,16
2,Jet Airways,Mumbai,Hyderabad,BOM → HYD,19:35,21:05,1h 30m,non-stop,No info,5678,3,Friday,15.0,0 days 01:30:00,21,19
3,Multiple carriers,Delhi,Banglore,DEL → BOM → COK,18:55,01:30 16 Jun,15h 10m,1 stop,In-flight meal not included,7408,5,Monday,6.0,0 days 15:10:00,1,18
4,Air India,Delhi,Cochin,DEL → COK,17:10,17:55,8h 20m,non-stop,No info,6724,6,Monday,24.0,0 days 08:20:00,17,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9445,Air India,Banglore,Cochin,BLR → MAA → DEL,19:30,19:50,8h 55m,1 stop,In-flight meal not included,5932,6,Wednesday,12.0,0 days 08:55:00,19,19
9446,IndiGo,Delhi,Cochin,DEL → BOM → COK,17:00,21:00,8h 35m,1 stop,No info,6838,3,Sunday,3.0,0 days 08:35:00,21,17
9447,Multiple carriers,Delhi,Cochin,DEL → BOM → COK,07:05,19:45,15h 15m,1 stop,No info,12615,3,Saturday,9.0,0 days 15:15:00,19,7
9448,Jet Airways,Kolkata,Banglore,CCU → BOM → BLR,08:20,19:50,12h 5m,1 stop,No info,10844,5,Saturday,18.0,0 days 12:05:00,19,8
9449,Air India,Kolkata,Banglore,CCU → GAU → IMF → DEL → BLR,14:30,23:15,8h 45m,3 stops,No info,15145,5,Thursday,9.0,0 days 08:45:00,23,14

In [80]:
#Filter
selector=(df_copy['Dep_Time_hr'] >=5) & (df_copy['Dep_Time_hr'] < 12)
selector2=(df_copy['Arrival_time_hr']>=17) & (df_copy['Arrival_time_hr']<20)

In [ ]:
selector.value_counts()

Dep_Time_hr
False    5118
True     4332
Name: count, dtype: int64

In [83]:
selector2.value_counts()

Arrival_time_hr
False    7411
True     2039
Name: count, dtype: int64

In [90]:
df_new=df_copy[selector & selector2]
df_new

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Month,WeekDay,Day,Duration_td,Arrival_time_hr,Dep_Time_hr
15,Multiple carriers,Delhi,Cochin,DEL → BOM → COK,11:25,19:15,7h 50m,1 stop,No info,7354,6,Wednesday,12.0,0 days 07:50:00,19,11
39,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,05:45,19:10,13h 25m,1 stop,No info,16736,3,Wednesday,6.0,0 days 13:25:00,19,5
48,Jet Airways,Delhi,Cochin,DEL → BOM → COK,11:30,19:00,7h 30m,1 stop,No info,14714,6,Wednesday,12.0,0 days 07:30:00,19,11
49,Multiple carriers,Delhi,Cochin,DEL → BOM → COK,07:30,19:00,11h 30m,1 stop,No info,9315,5,Thursday,9.0,0 days 11:30:00,19,7
51,Air India,Delhi,Kolkata,DEL → CCU → BOM → COK,11:40,19:15 13 Jun,2h 15m,2 stops,No info,13381,3,Friday,1.0,0 days 02:15:00,19,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9415,Jet Airways,Delhi,Cochin,DEL → BOM → COK,09:00,19:00,10h,1 stop,In-flight meal not included,10262,6,Saturday,15.0,0 days 10:00:00,19,9
9432,Jet Airways,Mumbai,Banglore,BOM → HYD,11:35,17:20,7h 15m,non-stop,No info,2071,5,Monday,6.0,0 days 07:15:00,17,11
9433,Multiple carriers,Delhi,Banglore,DEL → BOM → COK,08:25,19:15,12h 15m,1 stop,In-flight meal not included,16108,3,Sunday,24.0,0 days 12:15:00,19,8
9447,Multiple carriers,Delhi,Cochin,DEL → BOM → COK,07:05,19:45,15h 15m,1 stop,No info,12615,3,Saturday,9.0,0 days 15:15:00,19,7
9448,Jet Airways,Kolkata,Banglore,CCU → BOM → BLR,08:20,19:50,12h 5m,1 stop,No info,10844,5,Saturday,18.0,0 days 12:05:00,19,8

In [85]:
df['Arrival_Time'].head()

0    04:25 10 Jun
1    19:00 10 Jun
2           21:05
3    01:30 16 Jun
4           17:55
Name: Arrival_Time, dtype: str

In [86]:
print(selector.sum())
print(selector2.sum())
print((selector & selector2).sum())

4332
2039
922

In [ ]:
#Q7
#Encode the values of column 'WeekDay' as follows:
# Weekends (Sunday, Saturday) = 1
# all remaining five days = 0
# What is the most frequent (mode) WeekDay?

df['WeekDay'] = df['WeekDay'].replace({
    'Saturday': 1,
    'Sunday': 1,
    'Monday': 0,
    'Tuesday': 0,
    'Wednesday': 0,
    'Thursday': 0,
    'Friday': 0
})

In [93]:
df['WeekDay'].value_counts()

WeekDay
0    6651
1    2799
Name: count, dtype: int64